### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by a2231698193** [neuralchen/SimSwap#69]
Torch not compiled with CUDA enabled  这

**Comment by ftaker887** [comment]
Do everything exactly as it says here: https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md

**Comment by a2231698193** [comment]
no GPU  How do you use it? cpu

**Comment by a2231698193** [comment]
> 完全按照这里说的做所有事情：[https](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md) : [//github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md)

no GPU How do you use it? cpu

**Comment by woctezuma** [comment]
> no GPU How do you use it? cpu

At the end of the link provided by ftaker887:

> We expect users to have GPU with at least 3G memory. For those who do not, we provide [Colab Notebook implementation].

**Comment by andrewrush** [comment]
> no GPU How do you use it? cpu
Make just a few changes and you can run without GPU. No NVIDIA card required or any card, just 3Gb RAM (or less) and any processor, you should build or find CPU-compatible dependencies

**Comment by instant-high** [comment]
2Gb Nvidia GPU working for me.
CPU will be sloooooow...

**Comment by andrewrush** [comment]
> Torch not compiled with CUDA enabled 这
If don't have compatible GPU, You can use CPU. Install dependencies:

`conda create -n simswap python=3.6
conda activate simswap
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cpuonly -c pytorch
pip install --ignore-installed imageio
pip install insightface==0.2.1 onnxruntime moviepy`

Then use this powershell script: https://pastebin.com/y1FxV8jA

**Comment by andrewrush** [comment]
> 
> 
> 2Gb Nvidia GPU working for me.
> CPU will be sloooooow...

Yes, GPU backend is much better. But windows users with AMD and Intel cards has no choice.

**Comment by Hendiadyoin1** [comment]
@andrewrush can you reupload the powershell script, the link seems to be dead
Also To the maintainers, an adjustment to the documentation, that these paths exist would be nice

**Comment by woctezuma** [comment]
The link works fine here.

**Comment by Hendiadyoin1** [comment]
Ahh Adblocker was getting in my way..

**Comment by illtellyoulater** [comment]
Thanks @andrewrush! I could finally make it work! You are a king :)
